### ISSUE TITLE
关于Response返回规范的问题

### ISSUE THREAD

**Issue by SmRiley** [alipay/alipay-sdk-net-all#5]
比如以当面付为例,AlipayTradePrecreateResponse(**alipay.trade.precreate**的响应)Json主体在Body字段中,而AlipayTradeQueryResponse(**alipay.trade.query**)的Body字段无论是否请求成功都会返回null.虽然Json子健信息在其他字段中可以获取到,但是还是想问这个Body是遗漏了还是已经被弃用了?

**Comment by SmRiley** [comment]
你们给的示例文档中还是使用的Body吧.
![image](https://user-images.githubusercontent.com/45205313/75134090-2d5b2100-5718-11ea-91b8-b533fff5c681.png)

**Comment by SmRiley** [comment]
顺便给小白分享一下一个当面付的Demo [](https://github.com/SmRiley/Alipay_ToFace)

**Comment by antopen** [comment]
是因为alipay.trade.query的Response中出现了与body同名的业务字段，所以覆盖了基类的值。
可以尝试将Response转换成基类，再getBody，就可以获取到原始的响应JSON。

**Comment by Essensoft-Roc** [comment]
此类问题虽然可以解决，但容易造成困扰。希望能够重视下，应该规范下。[essensoft/payment](https://github.com/essensoft/payment) 开发时，将 [基类](https://github.com/essensoft/payment/blob/ea059e93f6e2736c7e882ec7b9073007582992a5/src/Essensoft.AspNetCore.Payment.Alipay/AlipayResponse.cs#L42) 改为 `ResponseBody`，结果 4.2.73版本 `AlipayOpenRequestBatchSendResponse` 又出现了 `ResponseBody`，真的挺无奈的。
