### ISSUE TITLE
AlipayTradeQueryResponse中的Body和AopResponse abstract基类中的Body同名问题

### ISSUE THREAD

**Issue by 554393109** [alipay/alipay-sdk-net-all#8]
AlipayTradeQueryResponse中的Body和AopResponse abstract基类中的Body同名，通过AlipayTradeQueryResponse的实例.Body取值时为null，无法获得基类中的原始报文供后续解析

![image](https://user-images.githubusercontent.com/3118906/78868996-6eb05180-7a76-11ea-8f11-73e663a40d8d.png)

**Comment by antopen** [comment]
可以尝试将Response转换成基类，再getBody，就可以获取到原始的响应JSON。
